name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rustfmt
      run: cargo fmt -- --check
    - name: Build
      run: cargo build
    - name: Build Editor
      run: cargo build --features editor
#    - name: Run tests
#      run: cargo test --all-features --verbose
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Clippy Editor
      run: cargo clippy --features editor -- -D warnings
